/* ============================================================
   Philly Guide — curated data
   Trip: Tue Jun 30 – Wed Jul 1, 2026 · Center City base
   source: "john"  = John's personal picks
   source: "alt"   = Also-Recommended (non-John's recs) + landmarks
   tripStatus.tue / .wed: { open: bool, text: "hours or note" }
   reservation: "walkin" | "recommended" | "required" | "ticket"
   ============================================================ */

const BANNER = {
  title: "Heads up — you're visiting during America250 🎆",
  body:
    "Your dates (Jun 30–Jul 1, 2026) land mid-celebration. The Wawa Welcome America Festival runs through Jul 4, so expect crowds, extra security, and road closures near Independence Hall / Liberty Bell — go to historic sites early. Several spots have unusual hours these two days; use the day toggle below to see what's open. Cash-only spots are flagged.",
};

// Category metadata: key, label, emoji, marker color
const CATEGORIES = [
  { key: "cheesesteaks", label: "Cheesesteaks", emoji: "🥩", color: "#b8291c" },
  { key: "finedining",   label: "Fine Dining",  emoji: "🍽️", color: "#5c3d9e" },
  { key: "casual",       label: "Casual & Brunch", emoji: "🥞", color: "#c27015" },
  { key: "cheap",        label: "Cheap Eats",   emoji: "💸", color: "#2f6f7a" },
  { key: "sweets",       label: "Coffee & Sweets", emoji: "☕", color: "#7a4010" },
  { key: "bars",         label: "Bars & Views", emoji: "🍸", color: "#1a5e9e" },
  { key: "landmarks",    label: "Landmarks",    emoji: "🏛️", color: "#2e4a5e" },
];

// John's baked-in must-go picks (shown pre-starred to everyone, on any device)
const MUSTGO = [
  "angelos", "suraya", "vernickfish", "dawa", "parc", "wawa", "nanzhou",
  "davidsmailaiwah", "pho75", "skycafe", "southsichuan", "orientexpress", "beilers", "skyhigh",
];

const PLACES = [
  /* ---------------- CHEESESTEAKS (John's) ---------------- */
  {
    id: "angelos",
    name: "Angelo's Pizzeria",
    category: "cheesesteaks",
    source: "john",
    cuisine: ["Cheesesteak", "Italian", "Hoagies"],
    blurb: "John's pick — get the Cooper Sharp cheesesteak.",
    why: "Hefty cheesesteaks bound with Cooper Sharp cheese on warm homemade sesame bread — a South Philly cult favorite.",
    address: "736 S 9th St, Philadelphia, PA 19147",
    phone: "(215) 922-0000",
    website: "",
    lat: 39.940685, lng: -75.157685,
    priceLevel: 2, priceText: "$15–22 / person",
    reservation: "walkin",
    resNote: "Walk-in only · CASH ONLY · no seating (eat on benches). Line can be 20–45+ min.",
    hours: "Wed–Sun 11 AM–7 PM · Closed Mon & Tue",
    tripStatus: { tue: { open: false, text: "Closed Tuesdays" }, wed: { open: true, text: "11 AM–7 PM" } },
    flag: "⚠️ Closed Tue Jun 30 — only reachable Wed Jul 1. Cash only.",
    reviews: [
      { platform: "Tripadvisor", rating: "4.5★", quote: "Ranked #191 of 2,500+ Philly restaurants — 'always a line, always worth it.'" },
      { platform: "One Bite", rating: "8.7/10", quote: "801 reviews — 'the bread makes it.'" },
    ],
  },
  {
    id: "johnsroastpork",
    name: "John's Roast Pork",
    category: "cheesesteaks",
    source: "john",
    cuisine: ["Roast Pork", "Cheesesteak"],
    blurb: "John's pick — try BOTH the roast pork sandwich and the cheesesteak.",
    why: "Often called the best cheesesteak in Philly, plus a James-Beard-winning roast pork (sharp provolone + broccoli rabe) frequently named the city's #1 sandwich.",
    address: "14 E Snyder Ave, Philadelphia, PA 19148",
    phone: "(215) 463-1951",
    website: "https://johnsroastpork.com",
    lat: 39.921059, lng: -75.144983,
    priceLevel: 2, priceText: "$13–20 / person",
    reservation: "walkin",
    resNote: "Walk-in only · CASH ONLY · limited outdoor seating. Lunch lines build fast — go before noon.",
    hours: "Tue–Sat 10 AM–5 PM · Closed Sun & Mon",
    tripStatus: { tue: { open: true, text: "10 AM–5 PM" }, wed: { open: true, text: "10 AM–5 PM" } },
    flag: "Lunch spot — closes 5 PM. Cash only.",
    reviews: [
      { platform: "Yelp", rating: "~4.5★", quote: "1,998 reviews — one of the most-reviewed sandwich spots in the city." },
      { platform: "Craig LaBan (Inquirer)", rating: "Champion", quote: "Named champion of his famous Cheesesteak Project." },
      { platform: "James Beard", rating: "Award", quote: "America's Classics award winner." },
    ],
  },
  {
    id: "dalessandros",
    name: "Dalessandro's Steaks & Hoagies",
    category: "cheesesteaks",
    source: "john",
    cuisine: ["Cheesesteak", "Hoagies"],
    blurb: "John's pick — worth the trip out (20–30 min from Center City).",
    why: "A 65-year Roxborough institution: finely chopped rib-eye, cheese mixed in just right, chunky onions. Open late, unlike the South Philly spots.",
    address: "600 Wendover St, Philadelphia, PA 19128",
    phone: "(215) 482-5407",
    website: "https://dalessandros.com",
    lat: 40.029513, lng: -75.205995,
    priceLevel: 2, priceText: "$10–20 / person",
    reservation: "walkin",
    resNote: "Walk-in · CASH ONLY (ATM inside) · counter service, they text when ready.",
    hours: "Mon–Thu 11 AM–10 PM · Fri–Sat 11 AM–11 PM · Sun 11 AM–9 PM",
    tripStatus: { tue: { open: true, text: "11 AM–10 PM" }, wed: { open: true, text: "11 AM–10 PM" } },
    flag: "~20–30 min from Center City (Roxborough). Open late — good dinner option. Cash only.",
    reviews: [
      { platform: "Google", rating: "4.4★", quote: "~13,400 reviews — 'the chop and cheese ratio is perfect.'" },
      { platform: "Yelp", rating: "4.1★", quote: "3,600+ reviews — a Roxborough classic." },
    ],
  },

  /* ---------------- CHEAP EATS (John's) ---------------- */
  {
    id: "wawa",
    name: "Wawa (Independence Mall flagship)",
    category: "cheap",
    source: "john",
    cuisine: ["Hoagies", "Convenience"],
    blurb: "John's pick — you have to experience Wawa. Build a hoagie on the touchscreen.",
    why: "Quintessential Philly rite of passage — use the touchscreen to build a hoagie. The Italian Shorti is the signature order.",
    address: "6th & Chestnut St (Public Ledger Bldg), Philadelphia, PA 19106",
    phone: "(267) 299-6269",
    website: "https://www.wawa.com",
    lat: 39.9486, lng: -75.1488,
    priceLevel: 1, priceText: "$6–12 / person",
    reservation: "walkin",
    resNote: "Walk-in · self-serve touchscreen ordering · cards accepted · most Center City stores 24/7.",
    hours: "Daily, early–late (most stores 24/7)",
    tripStatus: { tue: { open: true, text: "Open (24/7)" }, wed: { open: true, text: "Open (24/7)" } },
    flag: "",
    reviews: [
      { platform: "Philadelphia Mag", rating: "Top pick", quote: "Ranked the seasonal Gobbler the best Wawa sandwich (15 tested)." },
      { platform: "Local lore", rating: "Beloved", quote: "Flagship is 11,500 sq ft with a greenery wall & 'Philly Firsts' murals." },
    ],
  },
  {
    id: "halal",
    name: "Street Halal Carts (12th & Chestnut)",
    category: "cheap",
    source: "john",
    cuisine: ["Halal", "Street Food"],
    blurb: "John's pick — chicken/lamb over rice, white sauce + hot sauce a must.",
    why: "Cheap, fast, generously portioned chicken/lamb over rice from a Center City corner — the city's go-to budget street meal.",
    address: "NE corner, 12th & Chestnut St, Philadelphia, PA 19107 (carts also cluster near City Hall / 15th & JFK)",
    phone: "",
    website: "",
    lat: 39.9497, lng: -75.1620,
    priceLevel: 1, priceText: "$7–10 / platter",
    reservation: "walkin",
    resNote: "Walk-up · CASH preferred · locations can shift, verify on the day.",
    hours: "Typically lunch through evening (varies by cart)",
    tripStatus: { tue: { open: true, text: "Open (lunch–eve)" }, wed: { open: true, text: "Open (lunch–eve)" } },
    flag: "Cart locations shift — look around 12th & Chestnut or City Hall. Cash.",
    reviews: [
      { platform: "Yelp", rating: "Local fave", quote: "12th & Chestnut cart praised as 'by far the best one' in the area." },
      { platform: "Billy Penn", rating: "Staple", quote: "Covered as a Philly street-food staple — juicy chicken, generous portions." },
    ],
  },

  /* ---------------- CHINATOWN & ASIAN CHEAP EATS (John's) ---------------- */
  {
    id: "nanzhou",
    name: "Nan Zhou Hand Drawn Noodle House",
    category: "cheap",
    source: "john",
    cuisine: ["Chinese", "Noodles", "Hand-pulled"],
    blurb: "John's pick — hand-pulled noodles stretched to order.",
    why: "Watch the dough get hand-drawn at the counter, then slurp dumplings and noodle soup that punch far above the price.",
    address: "1022 Race St, Philadelphia, PA 19107 (Chinatown)",
    phone: "(215) 923-1550",
    website: "https://www.nanzhounoodle.com",
    lat: 39.9551, lng: -75.1556,
    priceLevel: 1, priceText: "$9–15 / person",
    reservation: "walkin",
    resNote: "Walk-in · CASH or Venmo only (no cards; ATM on-site).",
    hours: "Sun–Thu 11 AM–10 PM · Fri–Sat 11 AM–10:30 PM",
    tripStatus: { tue: { open: true, text: "11 AM–10 PM" }, wed: { open: true, text: "11 AM–10 PM" } },
    flag: "Cash only (Venmo OK).",
    reviews: [
      { platform: "Yelp", rating: "4.3★", quote: "'Best hand-drawn noodles in the city — watch them make it fresh.'" },
      { platform: "Google", rating: "4.4★", quote: "'Cheap, fast, delicious — bring cash though.'" },
    ],
  },
  {
    id: "tingwong",
    name: "Ting Wong",
    category: "cheap",
    source: "john",
    cuisine: ["Chinese", "Cantonese", "BBQ", "Roast Meats"],
    blurb: "John's pick — Chinatown's go-to roast duck & BBQ over rice.",
    why: "The lacquered roast duck and soy-sauce chicken are among the best in the city — served fast and cheap (a Best of Philly winner).",
    address: "138 N 10th St, Philadelphia, PA 19107 (Chinatown)",
    phone: "(215) 928-1883",
    website: "https://www.tingwongphilly.com",
    lat: 39.9553, lng: -75.1574,
    priceLevel: 1, priceText: "$10–20 / person",
    reservation: "walkin",
    resNote: "Walk-in · cash strongly preferred — bring cash to be safe.",
    hours: "Daily 8 AM–10 PM",
    tripStatus: { tue: { open: true, text: "8 AM–10 PM" }, wed: { open: true, text: "8 AM–10 PM" } },
    flag: "Roast duck specialist · bring cash.",
    reviews: [
      { platform: "Yelp", rating: "4.2★", quote: "'Roast duck over rice is incredible and a steal.'" },
      { platform: "Google", rating: "4.3★", quote: "'Best Cantonese BBQ in Chinatown — the crispy pork is perfect.'" },
    ],
  },
  {
    id: "tailake",
    name: "Tai Lake Seafood",
    category: "cheap",
    source: "john",
    cuisine: ["Chinese", "Cantonese", "Seafood"],
    blurb: "John's pick — Hong Kong-style seafood stalwart since 1988.",
    why: "Whole steamed fish and live shellfish prepared with serious Cantonese technique — an Inquirer-praised classic that holds up at any hour.",
    address: "134 N 10th St, Philadelphia, PA 19107 (Chinatown)",
    phone: "(215) 922-0698",
    website: "http://www.tailakeseafoodrest.com",
    lat: 39.9551, lng: -75.1576,
    priceLevel: 2, priceText: "$20–35 / person",
    reservation: "walkin",
    resNote: "Walk-in · cards accepted · hours vary by source — confirm by phone.",
    hours: "Daily ~1 PM–late (call to confirm)",
    tripStatus: { tue: { open: true, text: "~1 PM–late" }, wed: { open: true, text: "~1 PM–late" } },
    flag: "Great for groups · confirm hours by phone.",
    reviews: [
      { platform: "Yelp", rating: "4.1★", quote: "'Fresh whole fish, feels like Hong Kong, great for groups.'" },
      { platform: "Google", rating: "4.2★", quote: "'Authentic Cantonese seafood — the steamed fish was perfect.'" },
    ],
  },
  {
    id: "kensseafood",
    name: "Ken's Seafood",
    category: "cheap",
    source: "john",
    cuisine: ["Chinese", "Cantonese", "Seafood", "Late-night"],
    blurb: "John's pick — live-tank Cantonese seafood, open very late.",
    why: "One of the few places to get fresh whole fish and salt-and-pepper everything at 2 AM, with seafood pulled straight from the tank.",
    address: "1004 Race St, Philadelphia, PA 19107 (Chinatown)",
    phone: "(215) 925-3837",
    website: "",
    lat: 39.9548, lng: -75.1560,
    priceLevel: 2, priceText: "$15–30 / person",
    reservation: "walkin",
    resNote: "Walk-in · cards accepted · kitchen runs very late.",
    hours: "Daily ~4:30 PM–3 AM",
    tripStatus: { tue: { open: true, text: "4:30 PM–3 AM" }, wed: { open: true, text: "4:30 PM–3 AM" } },
    flag: "Late-night — opens at 4:30 PM.",
    reviews: [
      { platform: "Yelp", rating: "4.0★", quote: "'Late-night Cantonese seafood done right — the crab is excellent.'" },
      { platform: "Google", rating: "4.1★", quote: "'Open super late and the fish is genuinely fresh from the tank.'" },
    ],
  },
  {
    id: "davidsmailaiwah",
    name: "David's Mai Lai Wah",
    category: "cheap",
    source: "john",
    cuisine: ["Chinese", "Cantonese", "Late-night"],
    blurb: "John's pick — Chinatown's legendary post-midnight cure-all.",
    why: "The salt-and-pepper wings and 2 AM energy make it the definitive Philly late-night Chinese stop — just not on a Tuesday.",
    address: "1001 Race St, Philadelphia, PA 19107 (Chinatown)",
    phone: "(215) 627-2610",
    website: "https://mailaiwah.com",
    lat: 39.9550, lng: -75.1565,
    priceLevel: 1, priceText: "$10–18 / person",
    reservation: "walkin",
    resNote: "Walk-in · late-night · reportedly takeout-only as of 2026 — call to confirm dine-in.",
    hours: "Wed–Mon 4 PM–2:30 AM · Closed Tue",
    tripStatus: { tue: { open: false, text: "Closed Tuesdays" }, wed: { open: true, text: "4 PM–2:30 AM" } },
    flag: "⚠️ Closed Tue Jun 30 — only reachable Wed Jul 1. Late-night.",
    reviews: [
      { platform: "Yelp", rating: "4.0★", quote: "'Salt and pepper wings at 1 AM are unbeatable — crispy and cheap.'" },
      { platform: "Google", rating: "4.2★", quote: "'Classic late-night Chinatown spot, exactly what you want after drinks.'" },
    ],
  },
  {
    id: "pho75",
    name: "Pho 75",
    category: "cheap",
    source: "john",
    cuisine: ["Vietnamese", "Pho"],
    blurb: "John's pick — Philly's benchmark bowl of beef pho.",
    why: "A pared-down, decades-old pho specialist where a single steaming bowl with the loaded condiment tray is the whole point — a short hop south of Center City.",
    address: "1122 Washington Ave, Ste F, Philadelphia, PA 19147 (Bella Vista)",
    phone: "(215) 271-5866",
    website: "https://phillypho.com",
    lat: 39.9382, lng: -75.1628,
    priceLevel: 1, priceText: "$10–16 / person",
    reservation: "walkin",
    resNote: "Walk-in · CASH ONLY · this Washington Ave location is closest to Center City (not the Northeast one).",
    hours: "Daily ~9 AM–8 PM",
    tripStatus: { tue: { open: true, text: "9 AM–8 PM" }, wed: { open: true, text: "9 AM–8 PM" } },
    flag: "Cash only. Same plaza as Sky Cafe.",
    reviews: [
      { platform: "Yelp", rating: "4.3★", quote: "'The gold standard for pho in Philly — broth is deeply flavorful.'" },
      { platform: "Google", rating: "4.4★", quote: "'Simple menu, perfect pho, cash only so come prepared.'" },
    ],
  },
  {
    id: "skycafe",
    name: "Sky Cafe",
    category: "cheap",
    source: "john",
    cuisine: ["Indonesian"],
    blurb: "John's pick — under-the-radar Indonesian comfort food.",
    why: "Rendang, nasi campur and bakso done with real homestyle depth — one of the city's best and most overlooked Indonesian kitchens, in the same plaza as Pho 75.",
    address: "1122 Washington Ave, Ste B, Philadelphia, PA 19147 (South Philadelphia Plaza)",
    phone: "(215) 271-1983",
    website: "https://skycafephilly.com",
    lat: 39.9384, lng: -75.1623,
    priceLevel: 1, priceText: "$10–18 / person",
    reservation: "walkin",
    resNote: "Walk-in · closed Thursdays (open Tue & Wed). Same plaza as Pho 75.",
    hours: "Mon–Wed, Fri–Sun 11 AM–8 PM · Closed Thu",
    tripStatus: { tue: { open: true, text: "11 AM–8 PM" }, wed: { open: true, text: "11 AM–8 PM" } },
    flag: "Hidden gem · pairs with Pho 75 next door.",
    reviews: [
      { platform: "Yelp", rating: "4.4★", quote: "'Authentic Indonesian — the rendang and nasi campur are outstanding.'" },
      { platform: "Google", rating: "4.5★", quote: "'Hidden gem, tastes like home cooking, great value.'" },
    ],
  },
  {
    id: "seorabol",
    name: "Seorabol Center City",
    category: "casual",
    source: "john",
    cuisine: ["Korean", "BBQ"],
    blurb: "John's pick — Chris Cho's (@ChrisChefCho) Korean BBQ in Center City.",
    why: "Chris Cho's buzzy Center City spot carries on his family's 30-year Seorabol legacy — the SRB galbi on a sizzling hot stone is the move.",
    address: "1326 Spruce St, Philadelphia, PA 19107 (Center City)",
    phone: "(215) 608-8484",
    website: "https://www.srbtogo.com",
    lat: 39.9466, lng: -75.1626,
    priceLevel: 2, priceText: "$25–45 / person",
    reservation: "recommended",
    resNote: "Reservations recommended (walk-ins OK). No tabletop grill — BBQ is cooked in-kitchen, served on a sizzling stone plate.",
    hours: "Mon–Tue 4–11 PM · Wed–Sat 11:30 AM–11 PM · Sun 12–11 PM",
    tripStatus: { tue: { open: true, text: "4–11 PM" }, wed: { open: true, text: "11:30 AM–11 PM" } },
    flag: "Run by influencer chef Chris Cho (@ChrisChefCho). The original Olney location closed in 2025 — this is the one.",
    reviews: [
      { platform: "Yelp", rating: "4.3★", quote: "'Generous portions with a great array of complimentary banchan.'" },
      { platform: "Google", rating: "4.5★", quote: "'Chris Cho's spot lives up to the hype — the galbi on the hot stone is fantastic.'" },
    ],
  },
  {
    id: "southsichuan",
    name: "South Sichuan",
    category: "cheap",
    source: "john",
    cuisine: ["Chinese", "Sichuan"],
    blurb: "John's pick — a good friend's place; fiery, generous Sichuan.",
    why: "Authentic, affordable Sichuan — dan dan noodles, wontons in chili oil, mapo tofu — that rewards a short trip south of Center City.",
    address: "1548 S 19th St, Philadelphia, PA 19146 (Point Breeze)",
    phone: "(610) 803-1593",
    website: "",
    lat: 39.9275, lng: -75.1790,
    priceLevel: 1, priceText: "$12–20 / person",
    reservation: "walkin",
    resNote: "Walk-in / takeout-focused · order pickup or delivery online · opens 3 PM weekdays.",
    hours: "Tue–Fri 3–9:30 PM · Sat–Sun 12–10 PM · Closed Mon",
    tripStatus: { tue: { open: true, text: "3–9:30 PM" }, wed: { open: true, text: "3–9:30 PM" } },
    flag: "~1.5 mi south of Center City (Point Breeze) · takeout-focused · opens 3 PM.",
    reviews: [
      { platform: "Yelp", rating: "4.5★", quote: "'Generous portions; the wontons in chili oil and crispy chicken are standouts.'" },
      { platform: "Google", rating: "4.4★", quote: "'Legit Sichuan heat — dan dan noodles and Sichuan wings are the move.'" },
    ],
  },
  {
    id: "orientexpress",
    name: "Orient Express (Temple)",
    category: "cheap",
    source: "john",
    cuisine: ["Chinese", "Takeout"],
    blurb: "John's #1 Chinese takeout — a must every Philly visit (Temple campus).",
    why: "The quintessential cheap, fast campus Chinese counter by Temple — a personal must-have on every trip.",
    address: "1835 N 12th St, Ste 7, Philadelphia, PA 19122 (near Temple University)",
    phone: "(215) 236-5191",
    website: "",
    lat: 39.9847, lng: -75.1577,
    priceLevel: 1, priceText: "$7–12 / person",
    reservation: "walkin",
    resNote: "Walk-in takeout counter · bring cash to be safe. Summer/holiday hours are unreliable — call ahead.",
    hours: "Roughly Mon–Fri ~12–5 PM (tied to Temple's schedule)",
    tripStatus: { tue: { open: true, text: "~12–5 PM (confirm)" }, wed: { open: true, text: "~12–5 PM (confirm)" } },
    flag: "⚠️ ~2.5 mi north of Center City (Temple). May now be signed 'Johny's Express' — call to confirm name & summer hours.",
    reviews: [
      { platform: "Restaurant Guru", rating: "3.4★", quote: "'One of the best food stands around Temple — prompt, professional service.'" },
      { platform: "Yelp", rating: "~3.5★", quote: "'Cheap, fast, and gets the job done between classes.'" },
    ],
  },

  /* ---------------- MEDITERRANEAN / FINE DINING (John's) ---------------- */
  {
    id: "suraya",
    name: "Suraya",
    category: "finedining",
    source: "john",
    cuisine: ["Lebanese", "Mediterranean"],
    blurb: "John's all-time favorite — Lebanese market, café & garden.",
    why: "A destination Levantine oasis — market, café, restaurant and lush garden in one, serving Michelin-recognized Lebanese cooking.",
    address: "1528 Frankford Ave, Philadelphia, PA 19125 (Fishtown)",
    phone: "(215) 302-1900",
    website: "https://www.surayaphilly.com",
    lat: 39.973658, lng: -75.133972,
    priceLevel: 3, priceText: "Dinner ~$45–70 · lunch ~$10–20",
    reservation: "recommended",
    resNote: "Book via Resy 1–3 wks ahead. Walk-ins possible at bar / café / market. Brunch is weekends only (you'll miss it).",
    hours: "Dinner daily 5–10 PM · Wed lunch 11 AM–2 PM · Café/market daytime",
    tripStatus: { tue: { open: true, text: "Dinner 5–10 PM" }, wed: { open: true, text: "Lunch 11–2 · Dinner 5–10" } },
    flag: "Michelin-selected. Walk in to the café/market even without a reservation.",
    reviews: [
      { platform: "OpenTable", rating: "4.8★", quote: "'Exceptional Lebanese cuisine, impeccable service.'" },
      { platform: "Tripadvisor", rating: "4.4★", quote: "'Beyond what was expected — friendly and attentive.'" },
      { platform: "Yelp", rating: "~4.5★", quote: "'Vibrant mezze, stunning garden setting.'" },
    ],
  },
  {
    id: "zahav",
    name: "Zahav",
    category: "finedining",
    source: "john",
    cuisine: ["Israeli", "Mediterranean"],
    blurb: "John's pick — Philly's staple Mediterranean; availabilities now exist.",
    why: "Widely considered Philadelphia's best restaurant — a soulful set-menu Israeli feast anchored by the legendary braised lamb shoulder.",
    address: "237 St. James Pl, Philadelphia, PA 19106 (Society Hill)",
    phone: "(215) 625-8800",
    website: "https://www.zahavrestaurant.com",
    lat: 39.9463, lng: -75.1451,
    priceLevel: 4, priceText: "Tasting ~$90 · $120–150+ with drinks",
    reservation: "required",
    resNote: "Hard to get. Resy opens 28 days ahead at 11 AM ET (~Jun 2–3 for your dates) and sells out in minutes.",
    hours: "Dinner Tue–Sat ~5–9:30 PM · Closed Sun & Mon",
    tripStatus: { tue: { open: true, text: "5–9:30 PM" }, wed: { open: true, text: "5–9:30 PM" } },
    flag: "Book ASAP via Resy (28 days out, 11 AM ET).",
    reviews: [
      { platform: "Google", rating: "~4.6★", quote: "3,900+ reviews — 'the lamb shoulder is unforgettable.'" },
      { platform: "Yelp", rating: "4.5★", quote: "3,600+ reviews." },
      { platform: "James Beard", rating: "2019 Award", quote: "Outstanding Restaurant — the national top honor." },
    ],
  },
  {
    id: "vernick",
    name: "Vernick Food & Drink",
    category: "finedining",
    source: "john",
    cuisine: ["Modern American"],
    blurb: "John's pick — 'should be a Michelin-starred restaurant.'",
    why: "Greg Vernick's James-Beard-winning flagship — refined, ingredient-driven cooking in an intimate Rittenhouse brownstone. (Michelin 'Recommended,' 2025.)",
    address: "2031 Walnut St, Philadelphia, PA 19103 (Rittenhouse)",
    phone: "(267) 639-6644",
    website: "https://www.vernickphilly.com/vernick-food-and-drink",
    lat: 39.9506, lng: -75.1748,
    priceLevel: 4, priceText: "Tasting ~$155 · à la carte $90–150+",
    reservation: "required",
    resNote: "Hard to get. Resy releases the 1st of each month at 8 AM for the next month. Bar walk-ins are the fallback.",
    hours: "Tue–Sat 5–10 PM · Closed Sun & Mon",
    tripStatus: { tue: { open: true, text: "5–10 PM" }, wed: { open: true, text: "5–10 PM" } },
    flag: "James Beard Best Chef Mid-Atlantic · Michelin Recommended.",
    reviews: [
      { platform: "Google", rating: "4.7★", quote: "~1,065 reviews — 'flawless from start to finish.'" },
      { platform: "OpenTable", rating: "4.7★", quote: "~1,579 reviews." },
      { platform: "Tripadvisor", rating: "4.7★", quote: "#7 in Philly." },
    ],
  },
  {
    id: "vernickfish",
    name: "Vernick Fish",
    category: "finedining",
    source: "john",
    cuisine: ["Seafood", "Raw Bar"],
    blurb: "John's pick — the Vernick seafood sibling in the Comcast tower.",
    why: "Sleek upscale oyster bar in the Four Seasons / Comcast Technology Center — the glamorous, more accessible Vernick.",
    address: "1 N 19th St, Philadelphia, PA 19103 (Comcast Technology Center)",
    phone: "(215) 419-5055",
    website: "https://www.vernickfish.com",
    lat: 39.9547, lng: -75.1690,
    priceLevel: 4, priceText: "~$100–150 / person",
    reservation: "recommended",
    resNote: "Book via website / OpenTable — easier than the flagship. Dress code enforced.",
    hours: "Lunch Mon–Fri 11:30–2 · Dinner daily 4:30–10 PM",
    tripStatus: { tue: { open: true, text: "Lunch + Dinner" }, wed: { open: true, text: "Lunch + Dinner" } },
    flag: "Same building as Jean-Georges & SkyHigh — easy to combine.",
    reviews: [
      { platform: "OpenTable", rating: "4.8★", quote: "~2,003 reviews — 'best raw bar in the city.'" },
      { platform: "Yelp", rating: "Favorable", quote: "311 reviews." },
    ],
  },
  {
    id: "alpenrose",
    name: "Alpen Rose",
    category: "finedining",
    source: "john",
    cuisine: ["Steakhouse", "American"],
    blurb: "John's pick — amazing steak. Hidden brass-rose door on Sansom St.",
    why: "A tiny, hidden speakeasy-style steakhouse serving in-house dry-aged prime steaks over a wood-burning hearth — a special-occasion splurge.",
    address: "116 S 13th St, Philadelphia, PA 19107 (enter on Sansom St)",
    phone: "(215) 600-0709",
    website: "https://www.alpenrosephl.com",
    lat: 39.94971, lng: -75.162181,
    priceLevel: 4, priceText: "~$100–150+ / person",
    reservation: "required",
    resNote: "Effectively required — tiny ~50-seat room. Resy only, books ~30 days ahead. Best odds at 5–6 PM.",
    hours: "Dinner daily 5–10 PM",
    tripStatus: { tue: { open: true, text: "5–10 PM" }, wed: { open: true, text: "5–10 PM" } },
    flag: "Look for the unmarked matte-gray door with a brass rose + doorbell on Sansom St.",
    reviews: [
      { platform: "Google", rating: "4.7★", quote: "'Phenomenal — impeccable service, intimate ambiance.'" },
      { platform: "Yelp", rating: "~4.0★", quote: "'Moody wood-fire atmosphere, hidden-door experience.'" },
    ],
  },

  /* ---------------- JAPANESE (John's) ---------------- */
  {
    id: "doubleknot",
    name: "Double Knot",
    category: "finedining",
    source: "john",
    cuisine: ["Japanese", "Izakaya", "Sushi"],
    blurb: "John's all-time favorite — Japanese fusion izakaya.",
    why: "A buzzy, design-forward multi-level izakaya hidden beneath a Center City coffee-and-cocktail bar, with some of Philly's best sushi and robata.",
    address: "120 S 13th St, Philadelphia, PA 19107 (Midtown Village)",
    phone: "(215) 631-3868",
    website: "https://www.doubleknotphilly.com",
    lat: 39.94964, lng: -75.16210,
    priceLevel: 3, priceText: "~$50–100 / person (omakase higher)",
    reservation: "recommended",
    resNote: "Downstairs izakaya books out — reserve 2+ wks via Resy. Walk-ins mainly for Happy Hour (4–7 PM) & upstairs bar.",
    hours: "Tue 4–10 PM · Wed 4–11 PM · evening service only",
    tripStatus: { tue: { open: true, text: "4–10 PM" }, wed: { open: true, text: "4–11 PM" } },
    flag: "Walk in for Happy Hour 4–7 PM if you didn't book.",
    reviews: [
      { platform: "Google", rating: "4.6★", quote: "'Felt like you took a jet elsewhere — fast, attentive service.'" },
      { platform: "Tripadvisor", rating: "4.4★", quote: "'Food is INCREDIBLE, fish very fresh.'" },
    ],
  },
  {
    id: "zama",
    name: "Zama",
    category: "finedining",
    source: "john",
    cuisine: ["Japanese", "Sushi", "Omakase"],
    blurb: "John's pick — high-end Japanese; easiest of the sushi spots to book.",
    why: "Rittenhouse sushi institution since 2009 with daily-flown-in fish and an accessible $125 omakase — no booking battle.",
    address: "128 S 19th St, Philadelphia, PA 19103 (Rittenhouse)",
    phone: "(215) 568-1027",
    website: "https://www.zamaphilly.com",
    lat: 39.9498, lng: -75.1718,
    priceLevel: 3, priceText: "À la carte ~$50–90 · omakase ~$125",
    reservation: "recommended",
    resNote: "Resy / OpenTable — a few days' notice is usually fine. The easiest sushi reservation on this list.",
    hours: "Lunch Mon–Fri 12–2:30 · Dinner Sun–Thu 5–9, Fri–Sat 5–10",
    tripStatus: { tue: { open: true, text: "Lunch + Dinner" }, wed: { open: true, text: "Lunch + Dinner" } },
    flag: "",
    reviews: [
      { platform: "Google", rating: "~4.5★", quote: "'Reliable, fresh, friendly.'" },
      { platform: "Tripadvisor", rating: "4.2★", quote: "~190 reviews." },
    ],
  },
  {
    id: "morimoto",
    name: "Morimoto",
    category: "finedining",
    source: "john",
    cuisine: ["Japanese", "Omakase"],
    blurb: "John's pick — for the views & experience. Iron Chef Morimoto's flagship.",
    why: "Theatrical modern Japanese and a standout omakase in a sleek Karim-Rashid-designed room — Iron Chef Morimoto's original U.S. flagship.",
    address: "723 Chestnut St, Philadelphia, PA 19106 (Washington Sq West)",
    phone: "(215) 413-9070",
    website: "https://morimotorestaurant.com",
    lat: 39.9499, lng: -75.1532,
    priceLevel: 4, priceText: "À la carte ~$75–150+ · omakase ~$100–165",
    reservation: "recommended",
    resNote: "OpenTable — much easier than Zahav; 1–2 weeks out is comfortable for Tue/Wed.",
    hours: "Dinner Sun–Thu 5–10 · Fri–Sat 5–11 PM",
    tripStatus: { tue: { open: true, text: "5–10 PM" }, wed: { open: true, text: "5–10 PM" } },
    flag: "",
    reviews: [
      { platform: "Google", rating: "~4.7★", quote: "1,790+ reviews — 'the omakase is theater.'" },
      { platform: "Yelp", rating: "4.5★", quote: "2,200+ reviews." },
    ],
  },
  {
    id: "dawa",
    name: "DAWA Fishtown",
    category: "finedining",
    source: "john",
    cuisine: ["Japanese", "Sushi", "Ramen"],
    blurb: "John's pick — great value sushi from a friend (ex-Morimoto chef).",
    why: "A cult Fishtown hidden gem for some of Philly's best-value sushi and a generous 22-course bluefin omakase.",
    address: "1204 N Front St, Philadelphia, PA 19122 (Fishtown)",
    phone: "(215) 278-7671",
    website: "https://www.dawafish.com",
    lat: 39.969272, lng: -75.136266,
    priceLevel: 2, priceText: "À la carte affordable · omakase $180 (Fri/Sat only)",
    reservation: "walkin",
    resNote: "Walk-in for à la carte. Omakase is reservation-only, Fri & Sat 7 PM only (not available on a weekday).",
    hours: "Mon, Tue, Thu–Sat 12–10 · Sun 3–10 · CLOSED Wed",
    tripStatus: { tue: { open: true, text: "12–10 PM" }, wed: { open: false, text: "Closed Wednesdays" } },
    flag: "⚠️ Closed Wed Jul 1 — go Tue Jun 30. (Use the website address, not the outdated Girard Ave one.)",
    reviews: [
      { platform: "Yelp", rating: "~4.3★", quote: "155 reviews — 'best value sushi in Philly.'" },
      { platform: "The Infatuation", rating: "Top pick", quote: "Named among Philly's best omakase / hidden gems." },
    ],
  },

  /* ---------------- BRUNCH / CASUAL (John's) ---------------- */
  {
    id: "parc",
    name: "Parc",
    category: "casual",
    source: "john",
    cuisine: ["French", "Brunch", "Bistro"],
    blurb: "John's pick — good for brunch. Parisian café on Rittenhouse Square.",
    why: "Philadelphia's quintessential Parisian-café experience on Rittenhouse Square — gorgeous sidewalk seating and classic bistro fare.",
    address: "227 S 18th St, Philadelphia, PA 19103 (Rittenhouse)",
    phone: "(215) 545-2262",
    website: "https://parc-restaurant.com",
    lat: 39.94910, lng: -75.17067,
    priceLevel: 3, priceText: "~$30–60 · breakfast ~$15–30",
    reservation: "recommended",
    resNote: "Book via OpenTable. Walk-ins accepted but 30–60+ min waits at peak.",
    hours: "Weekday: breakfast 8–11 · lunch 11–3 · dinner 5–10",
    tripStatus: { tue: { open: true, text: "8 AM–10 PM" }, wed: { open: true, text: "8 AM–10 PM" } },
    flag: "Note: weekend-only brunch (you'll miss it) — do the 8–11 AM weekday breakfast instead.",
    reviews: [
      { platform: "OpenTable", rating: "4.8★", quote: "'Authentic Parisian atmosphere, sidewalk seating, amazing bread basket.'" },
      { platform: "Tripadvisor", rating: "4.5★", quote: "'Eggs Benedict and Croque Monsieur — like Paris.'" },
    ],
  },
  {
    id: "rouge",
    name: "Rouge",
    category: "casual",
    source: "john",
    cuisine: ["American", "French", "Brunch"],
    blurb: "John's pick — right next to Parc; famous Gruyère burger.",
    why: "The quintessential Rittenhouse Square patio scene — a 20+ year institution for cocktails and the famous Gruyère / caramelized-onion burger.",
    address: "205 S 18th St, Philadelphia, PA 19103 (Rittenhouse)",
    phone: "(215) 732-6622",
    website: "https://www.rouge98.com",
    lat: 39.9489, lng: -75.1718,
    priceLevel: 3, priceText: "~$30–60 · burger ~$20s–30s",
    reservation: "recommended",
    resNote: "Resy / OpenTable. Walk-ins possible but patio waits long on nice days.",
    hours: "Kitchen daily 12–10 PM (bar to midnight)",
    tripStatus: { tue: { open: true, text: "12–10 PM" }, wed: { open: true, text: "12–10 PM" } },
    flag: "Weekend-only brunch — but the patio + burger are great any day.",
    reviews: [
      { platform: "OpenTable", rating: "4.4★", quote: "'Cocktail on the sidewalk — great vibe.'" },
      { platform: "Yelp", rating: "3.5★", quote: "Signature Gruyère burger praised." },
    ],
  },
  {
    id: "mulherins",
    name: "Wm. Mulherin's Sons",
    category: "casual",
    source: "john",
    cuisine: ["Italian", "Brunch", "Pizza"],
    blurb: "John's pick — best brunch (scrambled eggs + steak). Weekday: dinner only.",
    why: "Some of Fishtown's best wood-fired Neapolitan pizza and handmade pasta in a restored 1890s whiskey-factory setting.",
    address: "1355 N Front St, Philadelphia, PA 19122 (Fishtown)",
    phone: "(215) 291-1355",
    website: "https://www.wmmulherinssons.com/restaurant",
    lat: 39.971731, lng: -75.135165,
    priceLevel: 3, priceText: "Dinner ~$40–70 · pizzas/pastas best value",
    reservation: "required",
    resNote: "Effectively required via Resy. Book ahead or dine very early/late for a walk-in.",
    hours: "Dinner Tue & Wed 5–9 PM (happy hour 4–6)",
    tripStatus: { tue: { open: true, text: "Dinner 5–9 PM" }, wed: { open: true, text: "Dinner 5–9 PM" } },
    flag: "⚠️ That famous scrambled-eggs-&-steak brunch is weekends only — you'll get the (excellent) dinner instead.",
    reviews: [
      { platform: "OpenTable", rating: "4.7★", quote: "'Reserve way in advance — but worth it.'" },
      { platform: "Google", rating: "4.6★", quote: "'Pizzas/pastas + historic ambiance.'" },
    ],
  },

  /* ---------------- BARS & VIEWS (John's) ---------------- */
  {
    id: "jeangeorges",
    name: "Jean-Georges Philadelphia",
    category: "bars",
    source: "john",
    cuisine: ["French", "Fine Dining", "Views"],
    blurb: "John's pick — for the views & experience. 59th floor of the Comcast tower.",
    why: "Philadelphia's premier sky-high fine dining — Jean-Georges cuisine in a two-story Norman-Foster glass room with panoramic views.",
    address: "1 N 19th St, 59th Floor, Philadelphia, PA 19103 (Comcast Technology Center)",
    phone: "(215) 419-5057",
    website: "https://www.jean-georgesphiladelphia.com",
    lat: 39.9549, lng: -75.1704,
    priceLevel: 4, priceText: "6-course tasting ~$228 · $250–350+ w/ wine",
    reservation: "required",
    resNote: "Effectively required via OpenTable / phone (opens ~90 days out). Book early for sunset seatings. Allow 3–4 hrs.",
    hours: "Dinner daily ~5–9:30 PM",
    tripStatus: { tue: { open: true, text: "Dinner ~5–9:30" }, wed: { open: true, text: "Dinner ~5–9:30" } },
    flag: "Big splurge with the best skyline view in the city.",
    reviews: [
      { platform: "OpenTable", rating: "4.9★", quote: "~1,053 reviews — 'stunning views, worth the splurge.'" },
      { platform: "Tripadvisor", rating: "4.2★", quote: "'Special-occasion perfection.'" },
    ],
  },
  {
    id: "skyhigh",
    name: "JG SkyHigh",
    category: "bars",
    source: "john",
    cuisine: ["Lounge", "Cocktails", "Views"],
    blurb: "John's pick — the lounge above Jean-Georges (60th floor). More casual.",
    why: "Philadelphia's highest lounge — cocktails and small plates with 60th-floor skyline views; a more casual alternative to the restaurant below.",
    address: "1 N 19th St, 60th Floor, Philadelphia, PA 19103 (Comcast Technology Center)",
    phone: "(215) 419-5059",
    website: "https://www.skyhighphiladelphia.com",
    lat: 39.9549, lng: -75.1704,
    priceLevel: 3, priceText: "Small plates $18–68 · ~$50–120+ / person",
    reservation: "recommended",
    resNote: "Dining room needs a reservation (OpenTable/phone); bar walk-ins welcome. Very busy at sunset.",
    hours: "Breakfast 7–10:30 · Lunch (Mon–Sat) 11:30–2:30 · Dinner 5–9:30 · bar later",
    tripStatus: { tue: { open: true, text: "All day → bar late" }, wed: { open: true, text: "All day → bar late" } },
    flag: "Easiest way to get the sky-high view — walk in to the bar for a sunset cocktail.",
    reviews: [
      { platform: "Restaurant Guru", rating: "4.6★", quote: "'Unbeatable views, great cocktails.'" },
      { platform: "OpenTable", rating: "Highly rated", quote: "~3,644 reviews." },
    ],
  },

  /* ---------------- LANDMARKS / MARKETS ---------------- */
  {
    id: "rtm",
    name: "Reading Terminal Market",
    category: "landmarks",
    source: "john",
    cuisine: ["Market", "Food Hall"],
    blurb: "John's pick — like Pike Place. 80+ vendors; don't miss Beiler's.",
    why: "Eat your way through a 130+ year-old indoor market — Amish baked goods, roast pork, cheesesteaks, all under one roof. 'America's Best Public Market.'",
    address: "51 N 12th St, Philadelphia, PA 19107",
    phone: "(215) 922-2317",
    website: "https://readingterminalmarket.org",
    lat: 39.9534, lng: -75.1590,
    priceLevel: 1, priceText: "Free entry · food ~$10–20",
    reservation: "walkin",
    resNote: "Walk-in. Most vendors take cards; ATMs on site. Busiest midday — go earlier.",
    hours: "Mon–Sat 8 AM–6 PM · Sun 9 AM–5 PM",
    tripStatus: { tue: { open: true, text: "8 AM–6 PM" }, wed: { open: true, text: "8 AM–6 PM" } },
    flag: "Inside: Beiler's Doughnuts & Tommy DiNic's roast pork (both listed separately here).",
    reviews: [
      { platform: "Google", rating: "4.7★", quote: "~38,800 reviews — 'you could eat here every meal.'" },
      { platform: "Tripadvisor", rating: "4.6★", quote: "#7 of 2,500+ Philly spots." },
    ],
  },
  {
    id: "libertybell",
    name: "Liberty Bell Center",
    category: "landmarks",
    source: "alt",
    cuisine: ["History", "Free"],
    blurb: "The icon — free, walk-in.",
    why: "See America's most iconic symbol of freedom — the cracked Liberty Bell — up close and free.",
    address: "526 Market St, Philadelphia, PA 19106",
    phone: "(215) 965-2305",
    website: "https://www.nps.gov/inde",
    lat: 39.9496, lng: -75.1503,
    priceLevel: 0, priceText: "FREE",
    reservation: "walkin",
    resNote: "Walk-in, first-come-first-served · free security screening. Go early during the festival week.",
    hours: "Daily 9 AM–7 PM (summer extended)",
    tripStatus: { tue: { open: true, text: "9 AM–7 PM" }, wed: { open: true, text: "9 AM–7 PM" } },
    flag: "Festival-week crowds & road closures nearby — visit early.",
    reviews: [
      { platform: "Google", rating: "4.6★", quote: "~19,900 reviews." },
      { platform: "Tripadvisor", rating: "4.3★", quote: "~24,850 reviews." },
    ],
  },
  {
    id: "independencehall",
    name: "Independence Hall",
    category: "landmarks",
    source: "alt",
    cuisine: ["History", "UNESCO"],
    blurb: "Where the Declaration & Constitution were signed. Timed ticket.",
    why: "Stand in the room where the Declaration of Independence and Constitution were debated and signed — a UNESCO World Heritage Site.",
    address: "520 Chestnut St, Philadelphia, PA 19106",
    phone: "(215) 965-2305",
    website: "https://www.nps.gov/inde",
    lat: 39.9489, lng: -75.1500,
    priceLevel: 0, priceText: "FREE tour · $1 ticket processing fee",
    reservation: "ticket",
    resNote: "Timed tickets required Mar–Dec via Recreation.gov (30-day rolling + day-before 5 PM release). 5–7 PM summer tours need no ticket. Will sell out July 4 week — book ahead.",
    hours: "Tours ~9 AM–4:40 PM (summer to 7 PM)",
    tripStatus: { tue: { open: true, text: "Timed tours" }, wed: { open: true, text: "Timed tours" } },
    flag: "Book a timed ticket in advance — festival week sells out.",
    reviews: [
      { platform: "Tripadvisor", rating: "4.5★", quote: "~9,200 reviews — 'goosebumps in that room.'" },
      { platform: "Google", rating: "~4.7★", quote: "'A must for any first visit.'" },
    ],
  },
  {
    id: "pma",
    name: "Philadelphia Museum of Art (Rocky Steps)",
    category: "landmarks",
    source: "alt",
    cuisine: ["Art", "Iconic Photo"],
    blurb: "The Rocky Steps are free 24/7 — museum interior is closed your days.",
    why: "Run the famous Rocky Steps (free, anytime) at one of America's great art museums.",
    address: "2600 Benjamin Franklin Pkwy, Philadelphia, PA 19130",
    phone: "(215) 763-8100",
    website: "https://philamuseum.org",
    lat: 39.9656, lng: -75.1810,
    priceLevel: 0, priceText: "Steps FREE · museum ~$25 adult",
    reservation: "walkin",
    resNote: "Steps & Rocky statue are free, outdoors, 24/7. Museum interior is closed Tue & Wed.",
    hours: "Museum Thu–Mon 10–5 · CLOSED Tue & Wed · Steps always open",
    tripStatus: { tue: { open: true, text: "Steps only (interior closed)" }, wed: { open: true, text: "Steps only (interior closed)" } },
    flag: "⚠️ Museum interior closed both your days — but the iconic steps & Rocky statue are free anytime.",
    reviews: [
      { platform: "Google", rating: "~4.6★", quote: "'Do the run — pure Philly.'" },
      { platform: "Tripadvisor", rating: "4.5★", quote: "World-class collection (when open)." },
    ],
  },
  {
    id: "lovepark",
    name: "LOVE Park (JFK Plaza)",
    category: "landmarks",
    source: "alt",
    cuisine: ["Photo Op", "Free"],
    blurb: "The classic LOVE sculpture photo, steps from City Hall.",
    why: "Snap the quintessential Philly photo at Robert Indiana's world-famous LOVE sculpture.",
    address: "1599 John F. Kennedy Blvd, Philadelphia, PA 19102",
    phone: "(215) 683-3600",
    website: "https://www.visitphilly.com/things-to-do/attractions/love-park/",
    lat: 39.9541, lng: -75.1656,
    priceLevel: 0, priceText: "FREE",
    reservation: "walkin",
    resNote: "Walk-in, open-air plaza.",
    hours: "Daily ~7 AM–10 PM",
    tripStatus: { tue: { open: true, text: "Open" }, wed: { open: true, text: "Open" } },
    flag: "",
    reviews: [
      { platform: "Tripadvisor", rating: "3.7★", quote: "'Quick, fun photo stop.'" },
    ],
  },
  {
    id: "cityhall",
    name: "City Hall Tower Tour",
    category: "landmarks",
    source: "alt",
    cuisine: ["View", "Architecture"],
    blurb: "Best 360° skyline view — under the William Penn statue.",
    why: "Ride 548 ft up to the open-air deck just beneath the William Penn statue for the city's best 360° skyline views.",
    address: "Visitor Center Room 121, 1400 JFK Blvd, Philadelphia, PA 19107",
    phone: "(267) 514-4757",
    website: "https://www.phlvisitorcenter.com/CityHallTowerTour",
    lat: 39.9526, lng: -75.1635,
    priceLevel: 1, priceText: "Tower tour ~$10–16",
    reservation: "ticket",
    resNote: "Tickets at Room 121 — the tower elevator is tiny, book ahead in summer. Weekdays only.",
    hours: "Tower tour Mon–Fri ~10 AM–3 PM",
    tripStatus: { tue: { open: true, text: "~10 AM–3 PM" }, wed: { open: true, text: "~10 AM–3 PM" } },
    flag: "Confirm holiday-week hours by phone.",
    reviews: [
      { platform: "Tripadvisor", rating: "4.3★", quote: "'Unbeatable view for the price.'" },
    ],
  },
  {
    id: "rittenhouse",
    name: "Rittenhouse Square",
    category: "landmarks",
    source: "alt",
    cuisine: ["Park", "Free"],
    blurb: "Leafy, elegant square — great for a coffee break.",
    why: "A leafy, elegant Center City square — one of William Penn's five original parks — perfect for people-watching.",
    address: "1800 Walnut St, Philadelphia, PA 19103",
    phone: "(215) 683-3600",
    website: "https://www.friendsofrittenhouse.org",
    lat: 39.9494, lng: -75.1719,
    priceLevel: 0, priceText: "FREE",
    reservation: "walkin",
    resNote: "Walk-in, open daily.",
    hours: "Daily ~dawn–11 PM",
    tripStatus: { tue: { open: true, text: "Open" }, wed: { open: true, text: "Open" } },
    flag: "Surrounded by Parc, Rouge, Zama, K'Far & Federal Donuts — a good home base.",
    reviews: [
      { platform: "Tripadvisor", rating: "4.6★", quote: "#32 of ~1,950 attractions." },
    ],
  },
  {
    id: "elfreths",
    name: "Elfreth's Alley",
    category: "landmarks",
    source: "alt",
    cuisine: ["History", "Photo Op"],
    blurb: "Oldest continuously inhabited street in the U.S. (since 1703).",
    why: "Walk a preserved cobblestone block of 18th-century rowhouses that feels like stepping into colonial Philadelphia.",
    address: "124–126 Elfreth's Alley, Philadelphia, PA 19106 (Old City)",
    phone: "(215) 574-0560",
    website: "https://www.elfrethsalley.org",
    lat: 39.9525, lng: -75.1432,
    priceLevel: 0, priceText: "Street FREE · museum $3",
    reservation: "walkin",
    resNote: "The street is free & walkable 24/7. The little museum is open Fri–Sun only (closed your days).",
    hours: "Street always open · museum Fri–Sun 12–4",
    tripStatus: { tue: { open: true, text: "Street open (museum closed)" }, wed: { open: true, text: "Street open (museum closed)" } },
    flag: "Combine with Old City + the Wawa flagship + Liberty Bell.",
    reviews: [
      { platform: "Tripadvisor", rating: "~4.5★", quote: "'Beautiful, quiet, photogenic.'" },
    ],
  },
  {
    id: "magicgardens",
    name: "Philadelphia's Magic Gardens",
    category: "landmarks",
    source: "alt",
    cuisine: ["Art", "Photo Op"],
    blurb: "Immersive mosaic labyrinth by Isaiah Zagar. Closed Tuesdays.",
    why: "A dazzling half-block immersive mosaic labyrinth by artist Isaiah Zagar — Philly's most photogenic art environment.",
    address: "1020 South St, Philadelphia, PA 19147",
    phone: "(215) 733-0390",
    website: "https://www.phillymagicgardens.org",
    lat: 39.9426, lng: -75.1594,
    priceLevel: 1, priceText: "Adult $15",
    reservation: "ticket",
    resNote: "Timed, self-guided tickets — book online ahead (often sells out, especially holiday week).",
    hours: "Wed–Mon 11 AM–6 PM · CLOSED Tue",
    tripStatus: { tue: { open: false, text: "Closed Tuesdays" }, wed: { open: true, text: "11 AM–6 PM" } },
    flag: "⚠️ Closed Tue Jun 30 — visit Wed Jul 1 only.",
    reviews: [
      { platform: "Google", rating: "4.6★", quote: "~4,120 reviews — 'unlike anything else.'" },
      { platform: "Tripadvisor", rating: "4.5★", quote: "~1,172 reviews." },
    ],
  },

  /* ---------------- ALSO RECOMMENDED (non-John's recs) ---------------- */
  {
    id: "beilers",
    name: "Beiler's Doughnuts",
    category: "sweets",
    source: "john",
    cuisine: ["Doughnuts", "Amish"],
    blurb: "John's pick — his favorite stop inside Reading Terminal Market.",
    why: "Fresh, hand-rolled Amish doughnuts in 50+ flavors made by a multi-generation Pennsylvania Dutch family — the Market's signature sweet.",
    address: "51 N 12th St, Philadelphia, PA 19107 (inside Reading Terminal Market)",
    phone: "(267) 318-7480",
    website: "https://beilersdoughnuts.com",
    lat: 39.9535, lng: -75.1588,
    priceLevel: 1, priceText: "$3–6 / person",
    reservation: "walkin",
    resNote: "Walk-up counter · cards accepted · lines build midday but move fast.",
    hours: "Mon–Sat 8 AM–6 PM (follows market hours)",
    tripStatus: { tue: { open: true, text: "8 AM–6 PM" }, wed: { open: true, text: "8 AM–6 PM" } },
    flag: "The Reading Terminal stall is the operating one (the old West Philly shop closed).",
    reviews: [
      { platform: "Yelp", rating: "High", quote: "1,654 reviews — 'a MUST at Reading Terminal.'" },
      { platform: "Fodor's", rating: "Top 20", quote: "Named one of America's 20 best dessert spots." },
    ],
  },
  {
    id: "dinics",
    name: "Tommy DiNic's",
    category: "cheap",
    source: "alt",
    cuisine: ["Roast Pork", "Sandwiches"],
    blurb: "Also-recommended — Philly's iconic roast pork inside Reading Terminal.",
    why: "Philly's most iconic roast pork sandwich — the city's beloved 'other' sandwich, Bourdain-anointed.",
    address: "Reading Terminal Market, 1136 Arch St, Philadelphia, PA 19107",
    phone: "(215) 923-6175",
    website: "https://www.tommydinics.com",
    lat: 39.9533, lng: -75.1591,
    priceLevel: 1, priceText: "Roast pork ~$16",
    reservation: "walkin",
    resNote: "Walk-up counter inside the market · expect a line at lunch.",
    hours: "Mon–Sat ~9 AM–5 PM",
    tripStatus: { tue: { open: true, text: "~9 AM–5 PM" }, wed: { open: true, text: "~9 AM–5 PM" } },
    flag: "Add sharp provolone + broccoli rabe. A perfect Reading Terminal combo with Beiler's.",
    reviews: [
      { platform: "Tripadvisor", rating: "4.5★", quote: "~#47 of 4,750 — 'better than a cheesesteak (to some).'" },
      { platform: "Yelp", rating: "Strong", quote: "2,462 reviews." },
    ],
  },
  {
    id: "federaldonuts",
    name: "Federal Donuts & Chicken",
    category: "sweets",
    source: "alt",
    cuisine: ["Doughnuts", "Fried Chicken"],
    blurb: "Also-recommended — donuts + Korean-style fried chicken (Zahav team).",
    why: "Cult-favorite donut-and-fried-chicken shop from the Zahav / CookNSolo team, now founder-run again at this Rittenhouse flagship.",
    address: "1909 Sansom St, Philadelphia, PA 19103 (Rittenhouse)",
    phone: "(215) 665-1101",
    website: "https://federaldonuts.com",
    lat: 39.9505, lng: -75.1730,
    priceLevel: 1, priceText: "Donuts ~$2–4 · chicken combos higher",
    reservation: "walkin",
    resNote: "Walk-in · donuts sell out, go early · menu was in flux after a 2026 reset, call to confirm.",
    hours: "~7 AM–6 PM daily (confirm)",
    tripStatus: { tue: { open: true, text: "~7 AM–6 PM" }, wed: { open: true, text: "~7 AM–6 PM" } },
    flag: "Use this Rittenhouse flagship — several other branches closed in 2026.",
    reviews: [
      { platform: "Google", rating: "~4.4★", quote: "'Hot fresh donuts + great fried chicken.'" },
    ],
  },
  {
    id: "middlechild",
    name: "Middle Child",
    category: "casual",
    source: "alt",
    cuisine: ["Sandwiches", "Brunch", "Luncheonette"],
    blurb: "Also-recommended — award-winning breakfast sandwich, open weekdays.",
    why: "Beloved luncheonette mashing up hoagie shops, Jewish delis and Greek diners — home of an award-winning breakfast sandwich.",
    address: "248 S 11th St, Philadelphia, PA 19107 (Washington Sq West)",
    phone: "(267) 930-8344",
    website: "https://middlechildphilly.com",
    lat: 39.9472, lng: -75.1594,
    priceLevel: 2, priceText: "Sandwiches ~$13–17",
    reservation: "walkin",
    resNote: "Walk-in / takeout only · small space, expect a wait at peak.",
    hours: "Tue–Fri 9 AM–3 PM · Sat–Sun 8–3 · Closed Mon",
    tripStatus: { tue: { open: true, text: "9 AM–3 PM" }, wed: { open: true, text: "9 AM–3 PM" } },
    flag: "Great real-brunch alternative since your weekend brunch spots are closed weekdays.",
    reviews: [
      { platform: "GMA", rating: "Best in U.S.", quote: "Its breakfast sandwich named 'Best Breakfast in America.'" },
      { platform: "Yelp", rating: "Strong", quote: "713 reviews, strongly positive." },
    ],
  },
  {
    id: "kfar",
    name: "K'Far Cafe",
    category: "sweets",
    source: "alt",
    cuisine: ["Israeli Bakery", "Coffee", "Brunch"],
    blurb: "Also-recommended — James-Beard-winning Israeli bakery by Rittenhouse.",
    why: "James-Beard-winning Israeli bakery café (Solomonov / Cogswell) for standout babka, bourekas and a coffee break by Rittenhouse.",
    address: "110 S 19th St, Philadelphia, PA 19103 (Rittenhouse)",
    phone: "(267) 800-7200",
    website: "https://www.kfarcafe.com",
    lat: 39.9503, lng: -75.1722,
    priceLevel: 2, priceText: "Pastries a few $ · bowls/sandwiches ~$10–16",
    reservation: "walkin",
    resNote: "Walk-in, first-come-first-served.",
    hours: "Daily ~8 AM–5 PM",
    tripStatus: { tue: { open: true, text: "~8 AM–5 PM" }, wed: { open: true, text: "~8 AM–5 PM" } },
    flag: "Perfect easy breakfast near Parc, Rouge & Zama.",
    reviews: [
      { platform: "Yelp", rating: "4.4★", quote: "~751 reviews — 'the babka is incredible.'" },
      { platform: "Google", rating: "~4.5★", quote: "'Best bakery in Center City.'" },
    ],
  },
  {
    id: "sabrinas",
    name: "Sabrina's Cafe",
    category: "casual",
    source: "alt",
    cuisine: ["Brunch", "American"],
    blurb: "Also-recommended — over-the-top brunch, open every day (BYOB).",
    why: "Philly's beloved, generous brunch institution — stuffed challah French toast and giant portions.",
    address: "1804 Callowhill St, Philadelphia, PA 19130 (Art Museum area)",
    phone: "(215) 636-9061",
    website: "https://www.sabrinascafe.com",
    lat: 39.9621, lng: -75.1707,
    priceLevel: 2, priceText: "~$14–20 / plate · BYOB",
    reservation: "walkin",
    resNote: "Walk-in only with a digital waitlist · weekday mornings far easier than weekends.",
    hours: "Daily 8 AM–3 PM",
    tripStatus: { tue: { open: true, text: "8 AM–3 PM" }, wed: { open: true, text: "8 AM–3 PM" } },
    flag: "True any-day brunch — a reliable pick for your weekday mornings.",
    reviews: [
      { platform: "Tripadvisor", rating: "4.5★", quote: "#24 of ~2,500 — 'the stuffed French toast!'" },
      { platform: "Yelp", rating: "4.0★", quote: "~2,150 reviews." },
    ],
  },
  {
    id: "assembly",
    name: "Assembly Rooftop Lounge",
    category: "bars",
    source: "alt",
    cuisine: ["Rooftop", "Cocktails", "Views"],
    blurb: "Also-recommended — reliable year-round Center City rooftop.",
    why: "The most reliable Center City rooftop for your dates — sweeping panoramas down the Parkway to the Art Museum at sunset.",
    address: "The Logan Hotel, 1840 Benjamin Franklin Pkwy, Philadelphia, PA 19103",
    phone: "(215) 963-2225",
    website: "https://www.assemblyrooftop.com",
    lat: 39.9569, lng: -75.1696,
    priceLevel: 3, priceText: "Cocktails + small plates · ~$12 walk-in cover · 21+",
    reservation: "recommended",
    resNote: "Reserve via Tock recommended; walk-ins subject to cover. 21+.",
    hours: "Daily ~4 PM–close",
    tripStatus: { tue: { open: true, text: "~4 PM–close" }, wed: { open: true, text: "~4 PM–close" } },
    flag: "A cheaper, year-round alternative to the sky-high lounges for a sunset drink.",
    reviews: [
      { platform: "Tripadvisor", rating: "4.1★", quote: "'Go for the Parkway view at golden hour.'" },
    ],
  },
  {
    id: "elvez",
    name: "El Vez",
    category: "casual",
    source: "alt",
    cuisine: ["Mexican"],
    blurb: "Also-recommended — festive Mexican, tableside guac & margaritas.",
    why: "Festive, central Mexican mainstay famous for tableside guacamole and punchy margaritas.",
    address: "121 S 13th St, Philadelphia, PA 19107 (Midtown Village)",
    phone: "(215) 928-9800",
    website: "https://www.elvezrestaurant.com",
    lat: 39.9492, lng: -75.1620,
    priceLevel: 2, priceText: "Tacos/entrées ~$10–20",
    reservation: "recommended",
    resNote: "Reservations (OpenTable) accepted; walk-ins welcome but loud/busy at peak.",
    hours: "Daily ~11:30 AM–10 PM",
    tripStatus: { tue: { open: true, text: "~11:30 AM–10 PM" }, wed: { open: true, text: "~11:30 AM–10 PM" } },
    flag: "Right by Double Knot & Alpen Rose in Midtown Village.",
    reviews: [
      { platform: "Yelp", rating: "4.0★", quote: "~2,745 reviews — 'great guac & margs.'" },
    ],
  },
  {
    id: "talulas",
    name: "Talula's Garden",
    category: "finedining",
    source: "alt",
    cuisine: ["Farm-to-Table", "American"],
    blurb: "Also-recommended — romantic garden-courtyard dining + amazing cheese.",
    why: "Romantic garden-courtyard farm-to-table dining on Washington Square — one of the city's best cheese selections.",
    address: "210 W Washington Sq, Philadelphia, PA 19106",
    phone: "(215) 592-7787",
    website: "https://talulasgarden.com",
    lat: 39.9471, lng: -75.1535,
    priceLevel: 4, priceText: "Entrées ~$30–48",
    reservation: "recommended",
    resNote: "Reservations strongly recommended via OpenTable / Tock.",
    hours: "Dinner Mon–Fri 5–10 PM",
    tripStatus: { tue: { open: true, text: "5–10 PM" }, wed: { open: true, text: "5–10 PM" } },
    flag: "A softer, easier-to-book fine-dining alternative to Zahav/Vernick.",
    reviews: [
      { platform: "Tripadvisor", rating: "4.6★", quote: "#5 of ~2,540 — 'the cheese course alone is worth it.'" },
      { platform: "OpenTable", rating: "Highly rated", quote: "14,000+ reviews." },
    ],
  },
];

// Transportation options (the 3 configurable modes)
const TRANSPORT = {
  walk: {
    key: "walk",
    label: "Walk + SEPTA",
    emoji: "🚶",
    gmaps: "transit",
    summary: "Center City is flat, gridded and very walkable — most sights are a 15–25 min walk. Use SEPTA subway for longer hops.",
    tips: [
      "Two subway lines: Market-Frankford (the 'El', E–W under Market St) and Broad Street Line (N–S). They meet at 15th St / City Hall.",
      "Fare $2.90/ride incl. up to 2 free transfers within 2 hrs — just tap a contactless card or phone (Apple/Google Pay). No need to buy a SEPTA Key card.",
      "Closest subway to Old City / Liberty Bell: 2nd St (Market-Frankford Line).",
      "Full SEPTA service is running normally in 2026.",
    ],
  },
  rideshare: {
    key: "rideshare",
    label: "Uber / Lyft",
    emoji: "🚗",
    gmaps: "driving",
    summary: "Easiest door-to-door, but downtown traffic is slow — for short hops walking is often faster.",
    tips: [
      "Short Center City trip (1–3 mi): about $10–18 (more with surge).",
      "PHL Airport → Center City: roughly $25–40 (often ~$35), 15–25 min. Expect surge near the July 4 holiday.",
      "For very short distances, Indego or walking usually beats waiting + traffic.",
    ],
  },
  bike: {
    key: "bike",
    label: "Indego Bike",
    emoji: "🚲",
    gmaps: "bicycling",
    summary: "Dock-based bike share blanketing Center City — great for flat, quick rides (e.g. to the Art Museum).",
    tips: [
      "Day Pass $15 = unlimited 60-min classic rides (best tourist value). Single ride $4.50/30 min.",
      "Get the Indego app (or use any station kiosk) to find docks, buy a pass and unlock. E-bikes cost a bit more per minute.",
      "Perfect for the flat Schuylkill River Trail and Parkway museums.",
    ],
  },
};

// Booking deep-links (verified). id -> { platform, url }
const BOOKING = {
  suraya:    { platform: "Resy",        url: "https://resy.com/cities/philadelphia-pa/venues/suraya" },
  doubleknot:{ platform: "Resy",        url: "https://resy.com/cities/philadelphia-pa/venues/doubleknot" },
  vernick:   { platform: "Resy",        url: "https://resy.com/cities/philadelphia-pa/venues/vernick-food-and-drink" },
  vernickfish:{ platform: "OpenTable",  url: "https://www.opentable.com/r/vernick-fish-philadelphia" },
  alpenrose: { platform: "Resy",        url: "https://resy.com/cities/philadelphia-pa/venues/alpen-rose" },
  zama:      { platform: "Resy",        url: "https://resy.com/cities/philadelphia-pa/venues/zama" },
  morimoto:  { platform: "OpenTable",   url: "https://www.opentable.com/morimoto-philadelphia" },
  jeangeorges:{ platform: "OpenTable",  url: "https://www.opentable.com/r/jean-georges-philadelphia-1" },
  skyhigh:   { platform: "OpenTable",   url: "https://www.opentable.com/r/skyhigh-philadelphia" },
  parc:      { platform: "OpenTable",   url: "https://www.opentable.com/parc" },
  rouge:     { platform: "Resy",        url: "https://resy.com/cities/philadelphia-pa/venues/rouge" },
  mulherins: { platform: "Resy",        url: "https://resy.com/cities/philadelphia-pa/venues/wm-mulherins-sons" },
  talulas:   { platform: "OpenTable",   url: "https://www.opentable.com/talulas-garden" },
  elvez:     { platform: "OpenTable",   url: "https://www.opentable.com/el-vez" },
  assembly:  { platform: "Tock",        url: "https://www.exploretock.com/thelogan" },
  zahav:     { platform: "Resy",        url: "https://resy.com/cities/philadelphia-pa/venues/zahav" },
  seorabol:  { platform: "OpenTable",   url: "https://www.opentable.com/s?term=Seorabol%20Center%20City%20Philadelphia" },
  independencehall: { platform: "Tickets", url: "https://www.recreation.gov/ticket/234639/ticket/90" },
  cityhall:  { platform: "Tickets",     url: "https://www.phlvisitorcenter.com/CityHallTowerTour" },
  magicgardens:{ platform: "Tickets",   url: "https://www.phillymagicgardens.org/hours-and-admission/general-admission-tickets/" },
};

// ---- 2-day plan generator config (rule-based, no LLM) ----
const TRIP_DAYS = [
  { key: "tue", label: "Tue · Jun 30", full: "Tuesday, June 30" },
  { key: "wed", label: "Wed · Jul 1", full: "Wednesday, July 1" },
];

// Which time-of-day blocks each category can fill (overridable per place)
const DAYPART_BY_CAT = {
  cheesesteaks: ["lunch", "dinner"],
  cheap:        ["lunch", "dinner", "snack"],
  sweets:       ["breakfast", "snack"],
  casual:       ["breakfast", "lunch", "dinner"],
  finedining:   ["dinner"],
  bars:         ["drinks", "dinner"],
  landmarks:    ["activity"],
};
const DAYPART_OVERRIDE = {
  parc: ["breakfast", "lunch", "dinner"], rouge: ["lunch", "dinner", "drinks"], mulherins: ["dinner"],
  middlechild: ["breakfast", "lunch"], sabrinas: ["breakfast", "lunch"], elvez: ["lunch", "dinner"],
  kfar: ["breakfast", "snack"], federaldonuts: ["breakfast", "snack"], beilers: ["breakfast", "snack"],
  dinics: ["lunch", "snack"], skyhigh: ["breakfast", "drinks", "dinner"], assembly: ["drinks"],
  jeangeorges: ["dinner"], suraya: ["lunch", "dinner"], zama: ["lunch", "dinner"],
  vernickfish: ["lunch", "dinner"], doubleknot: ["dinner", "drinks"], dawa: ["lunch", "dinner"],
  rtm: ["breakfast", "lunch", "activity"], wawa: ["snack", "lunch", "dinner"], halal: ["lunch", "snack", "dinner"],
  johnsroastpork: ["lunch"], angelos: ["lunch", "dinner"], dalessandros: ["lunch", "dinner"],
  davidsmailaiwah: ["dinner"], kensseafood: ["dinner"], tingwong: ["lunch", "dinner"],
  nanzhou: ["lunch", "dinner"], tailake: ["dinner"], pho75: ["lunch", "dinner"], skycafe: ["lunch", "dinner"],
  seorabol: ["lunch", "dinner"], southsichuan: ["dinner"], orientexpress: ["lunch"],
};

// Slot templates per pace. Meal slots always get filled; others respect interests.
const PACE_SLOTS = {
  relaxed: [
    { time: "9:00 AM",  label: "Breakfast",        daypart: "breakfast" },
    { time: "11:00 AM", label: "Morning sights",   daypart: "activity" },
    { time: "1:00 PM",  label: "Lunch",            daypart: "lunch" },
    { time: "3:30 PM",  label: "Afternoon sights", daypart: "activity" },
    { time: "7:00 PM",  label: "Dinner",           daypart: "dinner" },
  ],
  balanced: [
    { time: "8:30 AM",  label: "Breakfast",        daypart: "breakfast" },
    { time: "10:00 AM", label: "Morning sights",   daypart: "activity" },
    { time: "12:30 PM", label: "Lunch",            daypart: "lunch" },
    { time: "2:30 PM",  label: "Afternoon sights", daypart: "activity" },
    { time: "4:30 PM",  label: "Coffee / snack break", daypart: "snack" },
    { time: "6:00 PM",  label: "Sunset drink",     daypart: "drinks" },
    { time: "7:45 PM",  label: "Dinner",           daypart: "dinner" },
  ],
  packed: [
    { time: "8:00 AM",  label: "Breakfast",        daypart: "breakfast" },
    { time: "9:30 AM",  label: "Morning sights",   daypart: "activity" },
    { time: "11:00 AM", label: "Snack stop",       daypart: "snack" },
    { time: "12:30 PM", label: "Lunch",            daypart: "lunch" },
    { time: "2:00 PM",  label: "Afternoon sights", daypart: "activity" },
    { time: "3:30 PM",  label: "More to explore",  daypart: "activity" },
    { time: "5:00 PM",  label: "Coffee / snack break", daypart: "snack" },
    { time: "6:00 PM",  label: "Sunset drink",     daypart: "drinks" },
    { time: "7:30 PM",  label: "Dinner",           daypart: "dinner" },
  ],
};
const MEAL_DAYPARTS = ["breakfast", "lunch", "dinner"];

// Airport → Center City quick reference
const AIRPORT = [
  { mode: "SEPTA Airport Line (train)", cost: "$5", time: "~20–26 min", note: "Best value. ~Every 30 min to 30th St / Suburban / Jefferson stations." },
  { mode: "Uber / Lyft", cost: "~$25–40", time: "15–25 min", note: "Door-to-door; surge likely near July 4." },
  { mode: "Taxi", cost: "~$28.50 flat + tip", time: "15–25 min", note: "Regulated flat rate to Center City." },
];
